### ISSUE TITLE
Docker for windows path

### ISSUE THREAD

**Issue by stevemk14ebr** [act28/pia-openvpn-proxy#1] opened 2018-01-20 23:44 UTC
I'm using docker for windows, running the command given in the readme gives the following error:

> docker run -d --cap-add=NET_ADMIN --device=/dev/net/tun --name=vpn_proxy --dns=209.222.18.218 --dns=209.222.18.222 --restart=always -e "REGION=Netherlands" -e "USERNAME=*redacted*" -e "PASSWORD=*redacted*" -e "LOCAL_NETWORK=10.253.56.0/21" -v /etc/localtime:/etc/localtime:ro -p 8118:8118 act28/pia-openvpn-proxy 

> C:\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/8322352b9cebf07f6e6ea22511b310287ce84fe9053dbd1e559e638a9496835e/merged\\\" at \\\"/var/lib/docker/overlay2/8322352b9cebf07f6e6ea22511b310287ce84fe9053dbd1e559e638a9496835e/merged/etc/localtime\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

seems to be a an issue with the localtime path, what should that be set to?

**Comment by act28** [comment] 2019-06-20 04:47
You can safely leave it out for Windows. This is only needed if you need/want to override the default timezone set inside the container.

Closing as this is not a bug.

**Closed as completed by act28** 2019-06-20 04:47 UTC
Labels: 4 - Done
